Peds = {
    "cs_amandatownley",
    "cs_andreas",
    "cs_ashley",
    "cs_bankman",
    "cs_barry",
    "cs_beverly",
    "cs_brad",
    "cs_casey",
    "cs_chengsr",
    "cs_chrisformage",
    "cs_clay",
    "cs_dale",
    "cs_davenorton",
    "cs_debra",
    "cs_denise",
    "cs_dom",
    "cs_dreyfuss",
    "cs_drfriedlander",
    "cs_fabien",
    "cs_fbisuit_01",
    "cs_floyd",
    "cs_guadalope",
    "cs_gurk",
    "cs_hunter",
    "cs_janet",
    "cs_jewelass",
    "cs_jimmyboston",
    "cs_jimmydisanto",
    "cs_joeminuteman",
    "cs_johnnyklebitz",
    "cs_josef",
    "cs_josh",
    "cs_karen_daniels",
    "cs_lamardavis",
    "cs_lazlow",
    "cs_lestercrest",
    "cs_magenta",
    "cs_manuel",
    "cs_marnie",
    "cs_martinmadrazo",
    "cs_maryann",
    "cs_michelle",
    "cs_milton",
    "cs_molly",
    "cs_movpremf_01",
    "cs_movpremmale",
    "cs_mrk",
    "cs_mrs_thornhill",
    "cs_mrsphillips",
    "cs_natalia",
    "cs_nervousron",
    "cs_nigel",
    "cs_old_man1a",
    "cs_old_man2",
    "cs_omega",
    "cs_orleans",
    "cs_paper",
    "cs_patricia",
    "cs_priest",
    "cs_prolsec_02",
    "cs_russiandrunk",
    "cs_siemonyetarian",
    "cs_solomon",
    "cs_stevehains",
    "cs_stretch",
    "cs_tanisha",
    "cs_taocheng",
    "cs_taostranslator",
    "cs_tenniscoach",
    "cs_terry",
    "cs_tom",
    "cs_tomepsilon",
    "cs_tracydisanto",
    "cs_wade",
    "cs_zimbor",
    "g_f_importexport_01",
    "g_m_importexport_01",
    "hc_driver",
    "hc_gunman",
    "hc_hacker",
    "ig_abigail",
    "ig_agent",
    "ig_amandatownley",
    "ig_andreas",
    "ig_ashley",
    "ig_avon",
    "ig_bankman",
    "ig_barry",
    "ig_benny",
    "ig_beverly",
    "ig_brad",
    "ig_bride",
    "ig_car3guy1",
    "ig_car3guy2",
    "ig_casey",
    "ig_chef",
    "ig_chef2",
    "ig_chengsr",
    "ig_chrisformage",
    "ig_clay",
    "ig_claypain",
    "ig_dale",
    "ig_davenorton",
    "ig_denise",
    "ig_dom",
    "ig_dreyfuss",
    "ig_drfriedlander",
    "ig_fabien",
    "ig_fbisuit_01",
    "ig_floyd",
    "ig_guadalope",
    "ig_gurk",
    "ig_hunter",
    "ig_janet",
    "ig_jewelass",
    "ig_jimmyboston",
    "ig_jimmydisanto",
    "ig_joeminuteman",
    "ig_johnnyklebitz",
    "ig_josef",
    "ig_josh",
    "ig_karen_daniels",
    "ig_lamardavis",
    "ig_lazlow",
    "ig_lestercrest",
    "ig_magenta",
    "ig_manuel",
    "ig_marnie",
    "ig_maryann",
    "ig_michelle",
    "ig_milton",
    "ig_molly",
    "ig_movpremf_01",
    "ig_movpremmale",
    "ig_mrk",
    "ig_mrs_thornhill",
    "ig_mrsphillips",
    "ig_natalia",
    "ig_nervousron",
    "ig_nigel",
    "ig_old_man1a",
    "ig_old_man2",
    "ig_omega",
    "ig_orleans",
    "ig_ornate_banker",
    "ig_paper",
    "ig_patricia",
    "ig_priest",
    "ig_prolsec_02",
    "ig_russiandrunk",
    "ig_siemonyetarian",
    "ig_solomon",
    "ig_solomon_p",
    "ig_stevehains",
    "ig_stretch",
    "ig_talina",
    "ig_tanisha",
    "ig_taocheng",
    "ig_taostranslator",
    "ig_tenniscoach",
    "ig_terry",
    "ig_tom",
    "ig_tomepsilon",
    "ig_tracydisanto",
    "ig_tylerdix",
    "ig_wade",
    "ig_zimbor",
    "mp_f_avon",
    "mp_f_bennymech",
    "mp_f_boatstaff_01",
    "mp_f_cardesign_01",
    "mp_f_chbar_01",
    "mp_f_cocaine_01",
    "mp_f_counterfeit_01",
    "mp_f_deadhooker",
    "mp_f_execpa_01",
    "mp_f_execpa_02",
    "mp_f_forgery_01",
    "mp_f_freemode_01",
    "mp_f_helistaff_01",
    "mp_f_meth_01",
    "mp_f_misty_01",
    "mp_f_stripperlite",
    "mp_f_weed_01",
    "mp_g_m_pros_01",
    "mp_headtargets",
    "mp_m_avongoon",
    "mp_m_avonl",
    "mp_m_boatstaff_01",
    "mp_m_bogdangoon",
    "mp_m_claude_01",
    "mp_m_cocaine_01",
    "mp_m_counterfeit_01",
    "mp_m_exarmy_01",
    "mp_m_execpa_01",
    "mp_m_famdd_01",
    "mp_m_fibsec_01",
    "mp_m_forgery_01",
    "mp_m_freemode_01",
    "mp_m_g_vagfun_01",
    "mp_m_marston_01",
    "mp_m_meth_01",
    "mp_m_niko_01",
    "mp_m_securoguard_01",
    "mp_m_shopkeep_01",
    "mp_m_waremech_01",
    "mp_m_weapexp_01",
    "mp_m_weapwork_01",
    "mp_m_weed_01",
    "mp_s_m_armoured_01",
    "player_one",
    "player_two",
    "player_zero"
}

mugShot = {
    characterPos = {1853.8549804688, 3677.7626953125, 34.317993164062, 116.22047424316},
    cameraPos = {1852.087890625, 3676.6286621094, 34.317993164062},
}

introSteps = {
    ['Step 1'] = {
        coordsCam = {1795.8725585938, 3519.5078125, 40.417602539062},
        coordsPoint = {1808.8747558594, 3583.859375, 40.417602539062},
        message = [[^0
            Bine ai venit pe serverul ^3GTARPG^0! Serverul este unul de tip RPG, ceea ce poate ti se pare neobisnuit comparativ cu ce esti obisnuit sa joci. Ideea noastra a fost sa readucem
            nostalgia de pe ^3SA-MP^0 pe ^3FiveM^0 pentru ca ne ofera mult mai multe posibilitati de a evolua si a va oferii un mediu de joc cat mai placut.
        ]]
    },
    ['Step 2'] = {
        coordsCam = {1779.4417724609, 3696.0131835938, 40.87255859375},
        coordsPoint = {1818.0263671875, 3684.2900390625, 40.87255859375},
        message = "^0Serverul este unul bazat in ^3Paleto Bay & Sandy Shores^0. Spawnul tau va fi aici in Sandy, la sectia de Politie, unde iti vei seta si identitatea caracterului."
    },
    ['Step 3'] = {
        coordsCam = {1812.2506103516, 3622.6945800781, 40.417602539062},
        coordsPoint = {1785.1516113281, 3637.8330078125, 38.008056640625},
        message = "^0Aici este ^1Spitalul^0. Aici poti sa vii sa iti dai ^1heal^0 in caz ca nu ai HP-ul full. De asemenea, acesta este si locul factiunii ^1Paramedics^0. Factiune in care poti aplica la noi pe ^4Discord^0!"
    },
    ['Step 4'] = {
        coordsCam = {57.16484, 6580.971, 35.71643},
        coordsPoint = {60.75165, 6559.095, 31.92529},
        message = "^2Proprietatile^0 sunt si ele prezente la noi. Un exemplu sunt casele. Casele pot fi cumparate la orice nivel, in ambele locatii(Paleto Bay & Sandy Shores). Daca nu ai bani pentru o casa, poti platii chirie unui jucator ce detine una, iar daca iti cumperi o casa, o poti pune la inchiriat."
    }
}

jd = json.decode
je = json.encode

function containsSpaces(str)
  -- Loop through each character in the string
  for i = 1, #str do
    -- If the current character is a space, return true
    if str:sub(i, i) == " " then
      return true
    end
  end
  -- If no space is found, return false
  return false
end

function getTimestampAfterDays(days)
  -- Get the current Unix timestamp
  local currentTime = os.time()
  
  -- Calculate the number of seconds in a day
  local secondsInADay = 24 * 60 * 60

  -- Calculate the timestamp after the specified number of days
  local futureTime = currentTime + (days * secondsInADay)

  return futureTime
end

function getCurrentTimestamp()
  return os.time()
end